networks:
  api:
    driver: bridge

volumes:
  postgres_data:
    driver: local
services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks: 
      - api

  web:
    build: .
    command: gunicorn microservice.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks: 
      - api
    depends_on:
      - redis
      - db

  worker:
    build: .
    command: celery -A microservice worker --loglevel=info --pool=solo
    env_file:
      - .env
    networks: 
      - api
    depends_on:
      - redis
      - db

  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - api

