apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc  
  resources:
    requests:
      storage: 1Gi