apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres_password
  POSTGRES_DB: microservice_db
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  # Add environment variables from your .env file here
  # Example:
  # DATABASE_URL: postgres://postgres:postgres_password@postgres:5432/microservice_db
  # REDIS_URL: redis://redis:6379/0 