name: Docker CI/CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build . \
            --file Dockerfile \
            --tag joeuzo/api-worker:$(echo ${{ github.sha }} | cut -c1-7) \
            --tag joeuzo/api-worker:latest

      - name: Log in to Docker Hub
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" \
            | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker images
        if: github.event_name == 'push'
        run: |
          docker push joeuzo/api-worker:$(echo ${{ github.sha }} | cut -c1-7)
          docker push joeuzo/api-worker:latest
